/**
 * PDF export — generates a printable timeline view.
 * Uses browser's built-in print functionality with a styled print layout.
 * No server-side Puppeteer needed.
 */

import type { TimelineEvent, Viewport } from '../../types';
import { formatYear } from '../../utils/format';

/**
 * Generate a printable HTML document from timeline data and open print dialog.
 */
export function printTimeline(events: TimelineEvent[], viewport: Viewport, title?: string): void {
  const left = viewport.centerYear - viewport.span / 2;
  const right = viewport.centerYear + viewport.span / 2;

  const sorted = events
    .filter(e => e.year >= left && e.year <= right)
    .sort((a, b) => a.year - b.year);

  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>${escapeHtml(title || 'CHRONOS Timeline')}</title>
  <style>
    @page { margin: 1.5cm; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      color: #1a1a2e;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
    }
    h1 { font-size: 24px; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; }
    .subtitle { color: #666; font-size: 12px; margin-bottom: 24px; font-family: monospace; }
    .event {
      display: flex;
      gap: 16px;
      padding: 12px 0;
      border-bottom: 1px solid #eee;
      break-inside: avoid;
    }
    .event-year {
      min-width: 100px;
      font-family: monospace;
      font-size: 11px;
      color: #888;
      padding-top: 2px;
    }
    .event-emoji { font-size: 20px; }
    .event-title { font-weight: 600; font-size: 14px; }
    .event-desc { color: #555; font-size: 12px; margin-top: 2px; }
    .event-meta { color: #999; font-size: 10px; margin-top: 4px; }
    .event-citation { color: #888; font-size: 10px; font-style: italic; }
    .confidence-verified { color: #16a34a; }
    .confidence-likely { color: #ca8a04; }
    .confidence-speculative { color: #dc2626; }
    .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #ccc; color: #999; font-size: 10px; }
    .section-label { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #888; margin-top: 24px; margin-bottom: 8px; font-weight: 600; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title || 'CHRONOS Timeline')}</h1>
  <div class="subtitle">
    ${formatYear(left)} → ${formatYear(right)} · ${sorted.length} events
  </div>
  ${sorted.map(e => `
    <div class="event">
      <div class="event-year">${formatYear(e.year)}</div>
      <div>
        <div><span class="event-emoji">${e.emoji}</span> <span class="event-title">${escapeHtml(e.title)}</span></div>
        <div class="event-desc">${escapeHtml(e.description)}</div>
        ${e.confidence ? `<div class="event-meta"><span class="confidence-${e.confidence}">${e.confidence.toUpperCase()}</span></div>` : ''}
        ${e.citations?.length ? `<div class="event-citation">Sources: ${e.citations.map(c => escapeHtml(c.title || c.source)).join(', ')}</div>` : ''}
      </div>
    </div>
  `).join('')}
  <div class="footer">
    Generated by CHRONOS · ${new Date().toLocaleDateString()} · chronos.app
  </div>
</body>
</html>`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => printWindow.print();
  }
}

function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Export timeline segment as a styled HTML file (downloadable).
 */
export function downloadTimelineHTML(events: TimelineEvent[], viewport: Viewport, title?: string): void {
  const left = viewport.centerYear - viewport.span / 2;
  const right = viewport.centerYear + viewport.span / 2;
  const sorted = events.filter(e => e.year >= left && e.year <= right).sort((a, b) => a.year - b.year);

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${title || 'CHRONOS Timeline Export'}</title>
<style>
  body { font-family: system-ui; max-width: 800px; margin: 40px auto; padding: 0 20px; background: #0a0a1a; color: #e0e0e0; }
  h1 { color: #fff; }
  .event { padding: 12px 0; border-bottom: 1px solid #1a1a2e; display: flex; gap: 16px; }
  .year { min-width: 100px; font-family: monospace; color: #888; font-size: 12px; }
  .title { font-weight: 600; color: #fff; }
  .desc { color: #aaa; font-size: 13px; }
</style>
</head>
<body>
<h1>${title || 'CHRONOS Timeline'}</h1>
<p style="color:#666;font-family:monospace;font-size:12px">${formatYear(left)} → ${formatYear(right)} · ${sorted.length} events</p>
${sorted.map(e => `<div class="event"><div class="year">${formatYear(e.year)}</div><div><div class="title">${e.emoji} ${escapeHtml(e.title)}</div><div class="desc">${escapeHtml(e.description)}</div></div></div>`).join('')}
</body></html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'chronos-timeline.html';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
